backend:
    name: git-gateway
    branch: master # Branch to update (optional; defaults to master)

media_folder: static/uploads
public_folder: /uploads

collections:
    - name: 'blog'
      label: 'Blog'
      folder: 'static/posts'
      create: true
      fields:
          - { label: 'Slug', name: 'slug', widget: 'string' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Date', name: 'date', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
    - name: 'projects'
      label: 'Projects'
      folder: 'static/projects'
      create: true
      fields:
          - { label: 'Slug', name: 'slug', widget: 'string' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Date', name: 'date', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
